#
# This file is part of Brazil Data Cube Collection Builder.
# Copyright (C) 2019 INPE.
#
# Brazil Data Cube Collection Builder is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

version: '3.1'

networks:
  bdc_net:

services:
  redis:
    image: redis
    container_name: bdc-collection-builder-redis
    restart: "always"
    ports:
      - "6379:6379"
    networks:
      - bdc_net

  mq:
    image: rabbitmq:3-management
    container_name: bdc-collection-builder-rabbitmq
    hostname: bdc-collection-builder-rabbitmq
    restart: "always"
    volumes:
      - "./volumes/rabbitmq:/var/lib/rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - bdc_net

  postgres:
    image: mdillon/postgis
    container_name: bdc-collection-builder-pg
    restart: "always"
    volumes:
      - ./volumes/pg:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=bdc-collection-builder2019"
    networks:
      - bdc_net
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: bdc-collection-builder-api
    image: registry.dpi.inpe.br/brazildatacube/bdc-collection-builder:latest
    restart: "always"
    environment:
      - "REDIS_URL=redis://bdc-collection-builder-redis:6379"
      - "RABBIT_MQ_URL=pyamqp://guest@bdc-collection-builder-rabbitmq"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc"
      - "SQLALCHEMY_DATABASE_URI_AWS=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc_aws"
      - "DATA_DIR=/gfs"
    networks:
      - bdc_net
    ports:
      - "5000:5000"
    volumes:
      - ./secrets.json:/app/secrets.json
      - /gfs:/gfs
    command: >
      bash -c "bdc-collection-builder run --host 0.0.0.0"
    depends_on:
      - mq
      - redis
      - postgres

#  Celery
  worker-download:
    container_name: bdc-collection-builder-worker-download
    image: registry.dpi.inpe.br/brazildatacube/bdc-collection-builder:latest
    restart: "always"
    depends_on:
      - mq
      - api
    environment:
      - "REDIS_URL=redis://bdc-collection-builder-redis:6379"
      - "RABBIT_MQ_URL=pyamqp://guest@bdc-collection-builder-rabbitmq"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc"
      - "SQLALCHEMY_DATABASE_URI_AWS=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc_aws"
      - "DATA_DIR=/gfs"
    volumes:
      - /gfs:/gfs
      - ./secrets.json:/app/secrets.json
    command: >
      celery -A bdc_collection_builder.celery.worker:celery worker -l INFO --concurrency 4 -Q download
    networks:
      - bdc_net

  worker-atm-correction:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.atm
    container_name: bdc-collection-builder-worker-atm-correction
    image: registry.dpi.inpe.br/brazildatacube/bdc-collection-builder-atm:latest
    restart: "always"
    depends_on:
      - mq
      - api
    environment:
      - "REDIS_URL=redis://bdc-collection-builder-redis:6379"
      - "RABBIT_MQ_URL=pyamqp://guest@bdc-collection-builder-rabbitmq"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc"
      - "SQLALCHEMY_DATABASE_URI_AWS=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc_aws"
      - "DATA_DIR=/gfs"
      # The following variables are related to laSRC and ledaps execution.
      - "L8_AUX_DIR=/mnt/auxiliaries/L8"
      - "LASRC_AUX_DIR=/mnt/auxiliaries/L8"
      - "LEDAPS_AUX_DIR=/mnt/auxiliaries/ledaps"
    volumes:
      - /gfs:/gfs
      - /gfs/ds_data/auxiliaries:/mnt/auxiliaries
      - ./secrets.json:/app/secrets.json
    entrypoint: ["celery", "worker", "-A", "bdc_collection_builder.celery.worker:celery", "-l", "INFO", "--concurrency", "2", "-Q", "atm-correction"]
    networks:
      - bdc_net

  worker-publish:
    container_name: bdc-collection-builder-worker-publish
    image: registry.dpi.inpe.br/brazildatacube/bdc-collection-builder:latest
    restart: "always"
    depends_on:
      - mq
      - api
    volumes:
      - /gfs:/gfs
      - ./secrets.json:/app/secrets.json
    environment:
      - "REDIS_URL=redis://bdc-collection-builder-redis:6379"
      - "RABBIT_MQ_URL=pyamqp://guest@bdc-collection-builder-rabbitmq"
      - "DATA_DIR=/gfs"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc"
      - "SQLALCHEMY_DATABASE_URI_AWS=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc_aws"
    command: >
        celery worker -A bdc_collection_builder.celery.worker:celery -l INFO --concurrency 2 -Q publish
    networks:
      - bdc_net

  worker-harmonization:
    container_name: bdc_collection_builder-worker-harmonization
    image: registry.dpi.inpe.br/brazildatacube/bdc-collection-builder:latest
    restart: "always"
    depends_on:
      - mq
      - api
    environment:
      - "REDIS_URL=redis://bdc-collection-builder-redis:6379"
      - "RABBIT_MQ_URL=pyamqp://guest@bdc-collection-builder-rabbitmq"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc"
      - "DATA_DIR=/gfs"
      - "SQLALCHEMY_DATABASE_URI_AWS=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc_aws"
    volumes:
      - /gfs:/gfs
      - ./secrets.json:/app/secrets.json
    command: >
      celery -A bdc_collection_builder.celery.worker:celery worker -l INFO --concurrency 1 -Q harmonization
    networks:
      - bdc_net

  worker-upload:
    container_name: bdc-collection-builder-worker-upload
    image: registry.dpi.inpe.br/brazildatacube/bdc-collection-builder:latest
    restart: "always"
    depends_on:
      - mq
      - api
    volumes:
      - /gfs:/gfs
      - ./secrets.json:/app/secrets.json
    environment:
      - "REDIS_URL=redis://bdc-collection-builder-redis:6379"
      - "RABBIT_MQ_URL=pyamqp://guest@bdc-collection-builder-rabbitmq"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc"
      - "DATA_DIR=/gfs"
      - "SQLALCHEMY_DATABASE_URI_AWS=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc_aws"
    command: >
      celery worker -A bdc_collection_builder.celery.worker:celery -l INFO --concurrency 2 -Q upload
    networks:
      - bdc_net