version: '3.1'

networks:
  bdc_net:

services:
  redis:
    image: redis
    container_name: bdc-scripts-redis
    restart: "always"
    ports:
      - "6379:6379"
    networks:
      - bdc_net

  mq:
    image: rabbitmq:3-management
    container_name: bdc-scripts-rabbitmq
    restart: "always"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - bdc_net

  postgres:
    image: mdillon/postgis
    container_name: bdc-scripts-pg
    restart: "always"
    volumes:
      - ./volumes/pg:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=bdc-scripts2019"
    networks:
      - bdc_net
    ports:
      - "5435:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: bdc-scripts-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "bdc"
      PGADMIN_DEFAULT_PASSWORD: "Postgres2019!"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - bdc_net

  bdc-scripts:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: bdc-scripts-api
    image: ${IMAGE_BDC_SCRIPTS_FULL}
    restart: "always"
    environment:
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "REDIS_URL=redis://bdc-scripts-redis:6379"
      - "FLASK_APP=bdc_scripts"
      - "RABBIT_MQ_URL=pyamqp://guest@bdc-scripts-rabbitmq"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:bdc-scripts2019@bdc-scripts-pg:5432/bdc_scripts"
      - "SQLALCHEMY_DATABASE_URI_AWS=CHANGE_ME"
      - "DATA_DIR=/gfs"
    networks:
      - bdc_net
    ports:
      - "5000:5000"
    volumes:
      - ./credentials:/root/.aws/credentials
      - ./secrets.json:/app/secrets.json
      - /gfs:/gfs
    command: >
      bash -c "bdc-scripts db create && bdc-scripts db upgrade && bdc-scripts run --host 0.0.0.0"
    depends_on:
      - mq
      - redis
      - postgres

  espa-science:
    container_name: bdc-scripts-espa-science
    image: registry.dpi.inpe.br/rc_espa-science
    restart: always
    ports:
      - 5032:5032
    volumes:
      - ./rc_espa-science:/app
      - ./tmp:/tmp
      - ./:/home/espa/work-dir:rw
      - /gfs/Repository/Archive/LC8SR:/home/espa/output-data:rw
      - /:/home/espa/input-data:ro
      - /gfs/ds_data/auxiliaries:/usr/local/auxiliaries:rw
      - ./rc_espa-science/.usgs:/home/espa/.usgs:ro
    environment:
      L8_AUX_DIR: /usr/local/auxiliaries/L8
    networks:
      - bdc_net

  # sen2cor:
  #   container_name : bdc-scripts-sen2cor
  #   image: registry.dpi.inpe.br/rc_sen2cor:2.5.5
  #   restart: always
  #   ports:
  #     - 5031:5031
  #   volumes:
  #     - ./rc_sen2cor:/app
  #     - ./rc_sen2cor/root_255:/root
  #     - ./volumes/data/:/dados
  #     - /ds_data/CCI4SEN2COR:/home/lib/python2.7/site-packages/sen2cor/aux_data
  #   networks:
  #     - bdc_net

  sen2cor:
    container_name : bdc-scripts-sen2cor
    image: registry.dpi.inpe.br/rc_sen2cor:2.8.0
    restart: always
    ports:
      - 5031:5031
    volumes:
      - ./rc_sen2cor:/app
      - ./rc_sen2cor/root_280:/root
      - /:/dados
      - /gfs/ds_data/CCI4SEN2COR:/home/lib/python2.7/site-packages/sen2cor/aux_data
    networks:
      - bdc_net

#  Celery
  worker-download:
    container_name: bdc-scripts-worker-download
    image: ${IMAGE_BDC_SCRIPTS_FULL}
    restart: "always"
    depends_on:
      - mq
      - bdc-scripts
    environment:
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "REDIS_URL=redis://bdc-scripts-redis:6379"
      - "RABBIT_MQ_URL=pyamqp://guest@bdc-scripts-rabbitmq"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:bdc-scripts2019@bdc-scripts-pg:5432/bdc_scripts"
      - "SQLALCHEMY_DATABASE_URI_AWS=CHANGE_ME"
      - "DATA_DIR=/gfs"
    volumes:
      - ./credentials:/root/.aws/credentials
      - /gfs:/gfs
      - ./secrets.json:/app/secrets.json
    command: >
      celery -A bdc_scripts.celery.worker:celery worker -l INFO --concurrency 4 -Q download
    networks:
      - bdc_net

  worker-atm-correction:
    container_name: bdc-scripts-worker-atm-correction
    image: ${IMAGE_BDC_SCRIPTS_FULL}
    restart: "always"
    depends_on:
      - mq
      - bdc-scripts
    environment:
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "REDIS_URL=redis://bdc-scripts-redis:6379"
      - "RABBIT_MQ_URL=pyamqp://guest@bdc-scripts-rabbitmq"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:bdc-scripts2019@bdc-scripts-pg:5432/bdc_scripts"
      - "SQLALCHEMY_DATABASE_URI_AWS=CHANGE_ME"
      - "DATA_DIR=/gfs"
      - "ESPA_URL=http://bdc-scripts-espa-science:5032"
      - "SEN2COR_URL=http://bdc-scripts-sen2cor:5031"
    volumes:
      - ./credentials:/root/.aws/credentials
      - /gfs:/gfs
      - ./secrets.json:/app/secrets.json
    command: >
      celery -A bdc_scripts.celery.worker:celery worker -l INFO --concurrency 2 -Q atm-correction
    networks:
      - bdc_net

  worker-publish:
    container_name: bdc-scripts-worker-publish
    image: ${IMAGE_BDC_SCRIPTS_FULL}
    restart: "always"
    depends_on:
      - mq
      - bdc-scripts
    volumes:
      - ./credentials:/root/.aws/credentials
      - /gfs:/gfs
      - ./secrets.json:/app/secrets.json
    environment:
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "REDIS_URL=redis://bdc-scripts-redis:6379"
      - "RABBIT_MQ_URL=pyamqp://guest@bdc-scripts-rabbitmq"
      - "DATA_DIR=/gfs"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:bdc-scripts2019@bdc-scripts-pg:5432/bdc_scripts"
      - "SQLALCHEMY_DATABASE_URI_AWS=CHANGE_ME"
    command: >
        celery worker -A bdc_scripts.celery.worker:celery -l INFO --concurrency 2 -Q publish
    networks:
      - bdc_net

  worker-upload:
    container_name: bdc-scripts-worker-upload
    image: ${IMAGE_BDC_SCRIPTS_FULL}
    restart: "always"
    depends_on:
      - mq
      - bdc-scripts
    volumes:
      - ./credentials:/root/.aws/credentials
      - /gfs:/gfs
      - ./secrets.json:/app/secrets.json
    environment:
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "REDIS_URL=redis://bdc-scripts-redis:6379"
      - "RABBIT_MQ_URL=pyamqp://guest@bdc-scripts-rabbitmq"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:bdc-scripts2019@bdc-scripts-pg:5432/bdc_scripts"
      - "DATA_DIR=/gfs"
      - "SQLALCHEMY_DATABASE_URI_AWS=CHANGE_ME"
    command: >
      celery worker -A bdc_scripts.celery.worker:celery -l INFO --concurrency 2 -Q upload
    networks:
      - bdc_net