version: '3.1'

networks:
  bdc_net:

services:
  redis:
    image: redis
    container_name: bdc-collection-builder-redis
    restart: "always"
    ports:
      - "6379:6379"
    networks:
      - bdc_net

  mq:
    image: rabbitmq:3-management
    container_name: bdc-collection-builder-rabbitmq
    hostname: bdc-collection-builder-rabbitmq
    restart: "always"
    volumes:
      - "./volumes/rabbitmq:/var/lib/rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - bdc_net

  postgres:
    image: mdillon/postgis
    container_name: bdc-collection-builder-pg
    restart: "always"
    volumes:
      - ./volumes/pg:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=bdc-collection-builder2019"
    networks:
      - bdc_net
    ports:
      - "5432:5432"

  bdc-collection-builder:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: bdc-collection-builder-api
    image: registry.dpi.inpe.br/brazildatacube/bdc-collection-builder:latest
    restart: "always"
    environment:
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "REDIS_URL=redis://bdc-collection-builder-redis:6379"
      - "RABBIT_MQ_URL=pyamqp://guest@bdc-collection-builder-rabbitmq"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc"
      - "SQLALCHEMY_DATABASE_URI_AWS=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc_aws"
      - "DATA_DIR=/gfs"
    networks:
      - bdc_net
    ports:
      - "5000:5000"
    volumes:
      - ./secrets.json:/app/secrets.json
      - /gfs:/gfs
    command: >
      bash -c "bdc-collection-builder db create-db && bdc-collection-builder db upgrade && bdc-collection-builder run --host 0.0.0.0"
    depends_on:
      - mq
      - redis
      - postgres

  espa-science:
    container_name: bdc-collection-builder-espa-science
    image: registry.dpi.inpe.br/rc_espa-science
    restart: always
    ports:
      - 5032:5032
    volumes:
      - ./espa-science:/app
      - ./tmp:/tmp
      - ./:/home/espa/work-dir:rw
      - /gfs/Repository/Archive/LC8SR:/home/espa/output-data:rw
      - /:/home/espa/input-data:ro
      - /gfs/ds_data/auxiliaries:/usr/local/auxiliaries:rw
      - ./espa-science/.usgs:/home/espa/.usgs:ro
    environment:
      L8_AUX_DIR: /usr/local/auxiliaries/L8
    networks:
      - bdc_net

  sen2cor:
    container_name : bdc-collection-builder-sen2cor
    image: registry.dpi.inpe.br/rc_sen2cor:2.8.0
    restart: always
    ports:
      - 5031:5031
    volumes:
      - ./sen2cor:/app
      - ./sen2cor/root_280:/root
      - /:/dados
      - /gfs/ds_data/CCI4SEN2COR:/home/lib/python2.7/site-packages/sen2cor/aux_data
    networks:
      - bdc_net

#  Celery
  worker-download:
    container_name: bdc-collection-builder-worker-download
    image: registry.dpi.inpe.br/brazildatacube/bdc-collection-builder:latest
    restart: "always"
    depends_on:
      - mq
      - bdc-collection-builder
    environment:
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "REDIS_URL=redis://bdc-collection-builder-redis:6379"
      - "RABBIT_MQ_URL=pyamqp://guest@bdc-collection-builder-rabbitmq"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc"
      - "SQLALCHEMY_DATABASE_URI_AWS=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc_aws"
      - "DATA_DIR=/gfs"
    volumes:
      - /gfs:/gfs
      - ./secrets.json:/app/secrets.json
    command: >
      celery -A bdc_collection_builder.celery.worker:celery worker -l INFO --concurrency 4 -Q download
    networks:
      - bdc_net

  worker-atm-correction:
    container_name: bdc-collection-builder-worker-atm-correction
    image: registry.dpi.inpe.br/brazildatacube/bdc-collection-builder:latest
    restart: "always"
    depends_on:
      - mq
      - bdc-collection-builder
    environment:
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "REDIS_URL=redis://bdc-collection-builder-redis:6379"
      - "RABBIT_MQ_URL=pyamqp://guest@bdc-collection-builder-rabbitmq"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc"
      - "SQLALCHEMY_DATABASE_URI_AWS=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc_aws"
      - "DATA_DIR=/gfs"
      - "ESPA_URL=http://bdc-collection-builder-espa-science:5032"
      - "SEN2COR_URL=http://bdc-collection-builder-sen2cor:5031"
    volumes:
      - /gfs:/gfs
      - ./secrets.json:/app/secrets.json
    command: >
      celery -A bdc_collection_builder.celery.worker:celery worker -l INFO --concurrency 2 -Q atm-correction
    networks:
      - bdc_net

  worker-publish:
    container_name: bdc-collection-builder-worker-publish
    image: registry.dpi.inpe.br/brazildatacube/bdc-collection-builder:latest
    restart: "always"
    depends_on:
      - mq
      - bdc-collection-builder
    volumes:
      - /gfs:/gfs
      - ./secrets.json:/app/secrets.json
    environment:
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "REDIS_URL=redis://bdc-collection-builder-redis:6379"
      - "RABBIT_MQ_URL=pyamqp://guest@bdc-collection-builder-rabbitmq"
      - "DATA_DIR=/gfs"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc"
      - "SQLALCHEMY_DATABASE_URI_AWS=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc_aws"
    command: >
        celery worker -A bdc_collection_builder.celery.worker:celery -l INFO --concurrency 2 -Q publish
    networks:
      - bdc_net

  worker-upload:
    container_name: bdc-collection-builder-worker-upload
    image: registry.dpi.inpe.br/brazildatacube/bdc-collection-builder:latest
    restart: "always"
    depends_on:
      - mq
      - bdc-collection-builder
    volumes:
      - /gfs:/gfs
      - ./secrets.json:/app/secrets.json
    environment:
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "REDIS_URL=redis://bdc-collection-builder-redis:6379"
      - "RABBIT_MQ_URL=pyamqp://guest@bdc-collection-builder-rabbitmq"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc"
      - "DATA_DIR=/gfs"
      - "SQLALCHEMY_DATABASE_URI_AWS=postgresql://postgres:bdc-collection-builder2019@bdc-collection-builder-pg:5432/bdc_aws"
    command: >
      celery worker -A bdc_collection_builder.celery.worker:celery -l INFO --concurrency 2 -Q upload
    networks:
      - bdc_net